version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./:/var/www:cached
      - ./vendor:/var/www/vendor
    ports:
      - "9000:9000"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/etc/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php-fpm
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"