version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    depends_on:
      - redis
      - mysql
    volumes:
      - ./:/var/www:cached
      - ./vendor:/var/www/vendor
    ports:
      - "9000:9000"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/etc/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  composer:
    image: composer:latest
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php-fpm
  mysql:
    image: mysql:5.7.29
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: popular_videos
      MYSQL_USER: popular_videos
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db:/var/lib/mysql:cached
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
    db: